### ISSUE TITLE
`year` is not output in generated HTML page

### ISSUE THREAD

**Issue by kafumi** [cookpad/LicenseToolsPlugin#18]
Copyright years represented by `year` members in YAML are not output in generated licenses HTML page.

I have reproduced the issue with [v1.1.0](https://github.com/cookpad/LicenseToolsPlugin/releases/tag/1.1.0).

For example, following license definition should output `Copyright &copy; 2019, Square, Inc. All rights reserved.` as the copyright notice.

```yaml
- artifact: com.squareup.okhttp3:okhttp:+
  name: OkHttp
  copyrightHolder: Square, Inc.
  year: 2019
  license: The Apache Software License, Version 2.0
  licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.txt
  url: https://github.com/square/okhttp
```

However, it actually output `Copyright &copy; Square, Inc. All rights reserved.` which doesn't have year.

### Note

`YamlUtils` seems to forget to parse `year` member.
https://github.com/cookpad/LicenseToolsPlugin/blob/1.1.0/plugin/src/main/java/com/cookpad/android/plugin/license/util/YamlUtils.kt#L9-L35
